---
title: "Interim Report"
author: Patrick Toman^[<patrick.toman@uconn.edu>; Ph.D. student at Department of Statistics,
  University of Connecticut.]
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

#  Interim Report 

## Current Progress

The following tasks have been completed 

1. Dataset downloaded from NOAA website
  + Snowfall data from 3 weather stations in the Chicago metro area - O'Hare Int'l Airport,Midway Int'l Airport, and Park Forest
  + Data runs from 1960-07-01 to 2020-06-30
2. Snowfall data has been cleaned and formatted
  + Analysis of Missingness performed (< 1\% for Midway and O'Hare around 8\% for Park Forest) 
3. Basic EDA
  + Plots 
  + Summary Stats
4. Block Maxima GEV Models Implemented Using authors methods as template
  + Both stationary and trend non-stationary implemented
  + Functions compute return levels as well based off of authors code
  
## Next Items

1. Investigate whether missingness is an issue 
  + If it is an issue look at imputation methods
  + Primarily an issue for Park Forest station
2. Add in a spatial plot of Chicago to help illustrate spatial distribution of data
3. Implement other GEV models/ Study GP models (do we need to implement GP models to have an adequate project?)
  + Could improve on code substantially, possibly even unify into one function (kind of a pain though)
4. Implement code for Smith's Correction 
5. Bootstrapping code


  
