---
title: "Hierarchical Time Series Forecasting:"
subtitle: "A Case Study Using Electricity Load Data"
author:
  - Patrick Toman^[patrick.toman@uconn.edu>; Ph.D. student at
    Department of Statistics, University of Connecticut.]
date: "`r format(Sys.time(), '%d %B %Y')`"
documentclass: article
papersize: letter
fontsize: 11pt
bibliography: references.bib
biblio-style: apa
output:
  bookdown::html_document2
---

# Introduction

In many time series forecasting problems, the series can be disaggregated into a natural hierarchical or grouped structure. For example, daily taxi ridership in New York City can be disaggregated into a three tier hierarchy with the bottom level being the taxi usage in a specific taxi zone , the middle tier being the aggregated usage of zones within a given borough, and the top tier being the total daily usage across the entire city (@NYC_Data). Indeed, analysts and planners are often interested at forecasting at all levels of a time series hierarchy, a problem referred to as \textit{hierarchical time series forecasting}.


# Literature Review

Several different approaches have been given in the literature for the such with the most common being the \textit{top-down} (TD) and \textit{bottom-up} (BU) approaches. In the top-down setting, a typical approach is to build a  forecasting model for the highest level in the hierarchy and then forecasts are generated for the lower levels based off of a historically estimated proportion. Conversely, the \textit{bottom-up} approach involves forecasting the series only the time series at the bottom level and then aggregating them to generate forecasts at higher levels. A major drawback of the TD approach is that it often fails to model the volatile dynamics that are found in lower levels, while the BU approach results in forecasts that are not \textit{coherent}. \textit{Coherency} in this case refers to the property that the point forecasts of higher levels are equal to the sum of point forecasts at lower levels. To address the issues inherent with exclusively TD and BU approaches, Athanasopoulos et al. introduced a novel approach based on using forecasting the time series at each level and then using a regression model using the forecasts as inputs to determine an optimal forecast reconciliation and help create coherent forecasts (@ATHANASOPOULOS2009146). Furthermore, In a recent article, Abolghasemi et al.  applied several machine learning (ML) methods such as \textit{support vector regression},\textit{artificial neural networks}, and \textit{gradient boosting} with the goal of forecasting sales data with a weekly and monthly frequency (@abolghasemi2019machine). The authors found that the non-linear features of the sales time series were better handled by ML models as opposed to standard time series models such as ARIMAX and innovations state space models. In their conclusion, the authors note that they would like to apply their method to different dataset, particularly, high frequency hierarchical time due to the prevalence non-linear dynamics in such series.
 
# Project Idea 

Indeed, this project will expound on the ideas of Abolghamesi et al. by applying their methods on high frequency time series data. To accomplish this, we will apply their methodologies to electricity load data sampled at the hourly level for 4  major transmission organizations [PJM][PJM],[MISO][MISO],[NYISO][NYISO],and [ISO-New England][ISO-NE]. These organizations are major electricity utilities that in total provide most of the electrical power across most of the Midwest,South, and Northeast United States . Each of these organizations divide their hourly electric load data into smaller regional zones, therefore, we can model their time series as a hierarchical time series model with the top level being the aggregated hourly electricity load across the 4 transmission organizations, the first sub-level representing the aggregate load for a single organization, and the bottom nodes consisting of the sub-regional loads for each transmission organization. We will adhere to the general methodologies presented by Abolghamesi et al. by applying different forecast reconciliation methods as well as comparing ML method to more traditional time series models such as ARIMAX and Exponential Smoothing.     
 
# References 

[NYC-Taxi_Limo]: https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page
[PJM]: https://www.pjm.com/markets-and-operations/energy.aspx
[MISO]: https://www.misoenergy.org/markets-and-operations/real-time--market-data/market-reports/#t=10&p=0&s=MarketReportPublished&sd=desc
[NYISO]: https://www.nyiso.com/load-data
[ISO-NE]: https://www.iso-ne.com/isoexpress/web/reports/load-and-demand/-/tree/demand-by-zone

